---
title: "Model draft definition"
author: "Lorenzo Menichetti"
date: "1/10/2023"
output:
  tufte::tufte_html: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
 td{font-size: 10px;}
```
# Model definitions

The model components are:
<ol>
  <li>The decomposition model</li>
  <li>The two porosity functions, which are variables in the decomposition model</li>
  <li>Accessory functions to calculate the parameters for the porosity functions</li>
</ol>  

The decomposition model can be implemented by wrapping its differential form into a solver like `deSolve `, but since the model is nonlinear its solution vary at each time step (which corresponds to a variation of the porosity terms, see section [Decomposition model]). **This requires to run the ODE solver iteratively for each step**, and will add computational burden (one or two orders of magnitude depending on the time steps required).  

The other functions, needed to calculate the porosity parameters at each time step, are already integrated over time and can be used directly. To keep the structure of the package clean each function will be implemented separately and the connected in a hyerarchical structure.  

* Package
    * Decomposition model function
        * Differential model equations
    * Climate scaling function
    * Micro-porosity functions
    * Meso-porosity functions
        * Textural pore space function
        * Porosity slope function
            - Pore space volume function
            - Organic matter volume function

All references to equations numbere that follows refer to the original paper, Meurer et al., 2020.

## Decomposition model
The decomposition model is a compartmental model considering four components, two pools (Young and Old) for the mesopore fraction and two for the micropore fraction (equations 1 to 4):

\begin{equation}
    \begin{cases}
      \frac{dM_{Y_{(mes)}}}{dt} = I_m + \left( \frac{\phi_{mes}}{\phi_{mes}+\phi_{mic}}\right) \cdot I_r - k_Y \cdot M_{Y_{(mes)}}+ T_Y \\
      
      \frac{dM_{O_{(mes)}}}{dt} = \left( \epsilon \cdot k_Y \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot M_{O_{(mes)}} \right) + T_O\\
      
      \frac{dM_{Y_{(mic)}}}{dt} = \left( \frac{\phi_{mic}}{\phi_{mes}+\phi_{mic}}\right) \cdot I_r - k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}}- T_Y \\
      
      \frac{dM_{O_{(mic)}}}{dt} = \left( \epsilon \cdot k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot F_{prot} \cdot M_{O_{(mes)}} \right) - T_O
    \end{cases}
\end{equation}

The model has a feedback mechanism at the level of porosities $\phi_n$, so the system is instead:

\begin{equation}
    \begin{cases}
      \frac{dM_{Y_{(mes)}}}{dt} = I_m + \left( \frac{\phi_{mes}(t)}{\phi_{mes}(t)+\phi_{mic}(t)}\right) \cdot I_r - k_Y \cdot M_{Y_{(mes)}}+ T_Y \\
      
      \frac{dM_{O_{(mes)}}}{dt} = \left( \epsilon \cdot k_Y \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot M_{O_{(mes)}} \right) + T_O\\
      
      \frac{dM_{Y_{(mic)}}}{dt} = \left( \frac{\phi_{mic}(t)}{\phi_{mes}(t)+\phi_{mic}(t)}\right) \cdot I_r - k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}}- T_Y \\
      
      \frac{dM_{O_{(mic)}}}{dt} = \left( \epsilon \cdot k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot F_{prot} \cdot M_{O_{(mes)}} \right) - T_O
    \end{cases}
\end{equation}

Where it appears clear that the two porosity terms, $\phi_{mes} = f(M_{Y_{(mes)}}, M_{O_{(mes)}},M_{Y_{(mic)}}, M_{O_{(mic)}})$ and $\phi_{mic} = f(M_{Y_{(mic)}}, M_{O_{(mic)}})$, are dependent on the variation of the different C pools and everything is variable over time, introducing a nonlinearity in the system and defining the biggest peculiarity of this model.

### Attempting to rewrite the model in matrix notation

First we substitute the term $\left( \frac{\phi_{mes}(t)}{\phi_{mes}(t)+\phi_{mic}(t)}\right) = \varphi_{mes}$ and $\left( \frac{\phi_{mic}(t)}{\phi_{mes}(t)+\phi_{mic}(t)}\right) = \varphi_{mic}$

\begin{equation}
    \begin{cases}
      \frac{dM_{Y_{(mes)}}}{dt} = I_m + \varphi_{mes} \cdot I_r - k_Y \cdot M_{Y_{(mes)}}+ T_Y \\
      
      \frac{dM_{O_{(mes)}}}{dt} = \left( \epsilon \cdot k_Y \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot M_{O_{(mes)}} \right) + T_O\\
      
      \frac{dM_{Y_{(mic)}}}{dt} = \varphi_{mic} \cdot I_r - k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}}- T_Y \\
      
      \frac{dM_{O_{(mic)}}}{dt} = \left( \epsilon \cdot k_Y \cdot F_{prot} \cdot M_{Y_{(mes)}} \right) - \left( (1- \epsilon) \cdot k_O \cdot F_{prot} \cdot M_{O_{(mes)}} \right) - T_O
    \end{cases}
\end{equation}

A generic matrix notation for the system could be defined as

\begin{equation}
I_m(t) + I_r(t) \cdot N(C,t) + A(t) \cdot P(t) \cdot C(t)
\end{equation}

Considering separately the inputs from roots and from aboveground.


\begin{equation}
\frac{dC}{dt}=\begin{bmatrix}
              I_m\\
              0\\
              0\\
              0\\
              \end{bmatrix}+
              \begin{bmatrix}
              I_r\\
              0\\
              I_r\\
              0\\
              \end{bmatrix} \cdot
               \begin{bmatrix}
              \varphi_{mes} & 0 & 0 & 0\\
              0 & 1 & 0 & 0\\
              0 & 0 & \varphi_{mic} & 0\\
              0 & 0 & 0 & 1\\
              \end{bmatrix}+
               \begin{bmatrix}
              -k_y & \epsilon & 0 & 0\\
              0 & -k_o & 0 & 0\\
              T_Y & 0 & -k_y & \epsilon\\
              0 & T_O & 0 & -k_o\\
              \end{bmatrix} \cdot
                 \begin{bmatrix}
              1 & 0 & 0 & 0\\
              0 & 1 & 0 & 0\\
              0 & 0 & F_{prot} & 0\\
              0 & 0 & 0 & F_{prot}\\
              \end{bmatrix} \cdot
               \begin{bmatrix}
              M_{Y_{mes}}\\
              M_{O_{mes}}\\
              M_{Y_{mic}}\\
              M_{O_{mic}}
              \end{bmatrix}
\end{equation}

### Climatic scaling of decomposition
The climatic scaling of decomposition can be introduced in the model as in the ICBM model from which this model is derived, with a multiplier oscillating around 1 (which is the standard climate in Ultuna, where the model was developed) that multiplies the two kinetics $k_Y$ and $k_O$. The calculation of this term, called $r_e$, is already developed (https://github.com/ilmenichetti/reclim), but **adding this scaling can require a recalibration of the model on multiple sites**. The model present nonlinear interactions and it is unlikely that this has no effect on the calibration, and while it would work in Ultuna (where $r_e$ is by defintion 1) this might make the model predictions unreliable when extrapolating on new sites. This is because the $r_e$ scaling has been developed and tested on the standard ICBM model, which does not behave in the same way, and extending it to another model requires at least a validation.

## Porosity variation functions
We need to define the functions of variation of the two porosities considered, mesopores $\phi_{mes}$ and micropores $\phi_{mic}$. These depends on some external constants, and ultimately on the variation of the organic C pools.

### Microporosity function
The microporosity depends on the variation of the organic matter associated with micropores, $M_{Y_{(mic)}}$ and $M_{O_{(mic)}}$, plus some additional constants:

$$ \phi_{mic} = \frac{\left[ f_{agg} \left(  \frac{M_{Y_{mic}}+ M_{O_{mic}}}{ \gamma_o} \right)\right] + (F_{text_{mic}} \Delta_z \phi_{min})}{\Delta_z}$$ (eq. 24)
Where $\Delta_z$ is the depth considered, $F_{text_{mic}}$ is the proportion of the textural pore spaces that comprises micropores and $f_{agg}$ is an aggregation factor defined as the slope of the linear relationship assumed between the volume of aggregation pore spaces and the volume of organic matter. The constant  $F_{text_{mic}}$ is calculated according to what specified in the section [Textural pore space function] while the constant $f_{agg}$ is calculated according to  what specified in the section [Porosity slope calculation]. $\gamma_o$ is the density of organic matter (kg m$^{-3}$)

### Mesopore function
The mesopore porosity function is a result of micropore and matrix porosities:
$$ \phi_{mes} = \phi_{mat}-\phi_{mic} $$ (eq. 25)
Matrix porosity depends on all the organic pools plus additional constants:
$$\phi_{mat} = \frac{\left[ f_{agg} \frac{M_{s_{0}}}{ \gamma_o} \right] + \Delta_z \phi_{min})}{\Delta_z}$$ (eq. 13)
The variable $M_{s_{0}}$ is the sum of all the organic matter pools:
$$M_{s_{0}} = M_{Y_{(mes)}} + M_{O_{(mic)}} + M_{Y_{(mic)}} + M_{O_{(mic)}}$$ (eq. 8)

## Textural pore space function
The textural pore space can be calculated from ^[Katha, you write that "It should be feasible to estimate Ftext(mic) from data on soil texture, since pore and particle size distributions are similar in the absence of structural pores". How can we do that?]
$$F_{text_{mic}} = $$

## Porosity slope calculation
This is a linear regression so we can define it as:
$$f_{agg} = (y2-y1)/(x2-x1)$$
Where $x_n$ and $y_n$ are the coordinates ^[Katha, what are the coordinates of the linear regression here? You describe them as just one value, volume, but for a linear regression we need a two-dimensional space] of the volume of the aggregation pore space $V_{agg}$ and the volume of organic matter. $V_{s_o}$.

## Volume of pore space and organic matter calculation

$$V_{agg} =$$

$$V_{s_o} =$$.


# References
Meurer, K.H.E., Chenu, C., Coucheney, E., Herrmann, A.M., Keller, T., Kätterer, T., Nimblad Svensson, D., Jarvis, N., 2020. Modelling dynamic interactions between soil structure and the storage and turnover of soil organic matter. Biogeosciences 17, 5025–5042. https://doi.org/10.5194/bg-17-5025-2020

