---
title: "TwoPools nonlinearity in inputs"
author: "Lorenzo Menichetti"
date: "2023-01-18"
output:
  html_document: default
  pdf_document: default
---


# Equation

Matrix notation of a simplified system could be defined as
\begin{equation}
\frac{dC}{dt}=I(t) \cdot N(C,t) + A(t) \cdot C(t)
\end{equation}
Inputs $I$ are modified by the term $theta$ which is a function of humified C ($C_O$).
We consider only two pools for simplicity, $C_y$ and $C_o$. We adopt the notation of Jarvis and Meurer for the ICBM model (just a two-pools linear model), substituting $h$ with $\epsilon$.  

Developing the matrices the model becomes:

\begin{equation}
\frac{dC}{dt}=\begin{bmatrix}
              I\\
              0
              \end{bmatrix} \cdot
               \begin{bmatrix}
              \theta (C_o) & 0 \\
              0 & 1 
              \end{bmatrix}+
               \begin{bmatrix}
              -k_y & \epsilon\\
              0 & -k_o
              \end{bmatrix} \cdot
               \begin{bmatrix}
              C_y\\
              C_o
              \end{bmatrix}
\end{equation}

The nonlinearity defined by $\theta$ is a generic function of the old C pool content $C_o$, $\theta = f(C_o(t))$.


# Draft parameter values

We can start from the 1996 ICBM parameterization for the parameter values:
$k_y=0.8$, $k_o=0.00605$ and $\eta=h=0.13$, ignoring the climatic scaling for the moment.  

<div class="alert alert-info">
  <strong>Note:</strong> the $\epsilon$ parameter for ICBM is dependent on input quality, this must be considered in the multimodel comparison also for all other models.
</div>