---
title: "Subproject_desacription"
author: "Lorenzo Menichetti"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aims of the project  
1. Produce aggregated national predictions on the C sequestration potential of Swedish agricultural soils with included model structural uncertainty  
2.  Understand the impact of various factors on prediction robustness 
To achieve these two goal, we will combine a selection of compartmental first-order SOC models, calibrate the whole ensemble on a set of Swedish long-term experiments, and then analyze the results of the ensemble in respect to various factors (for example climate, location, edaphic conditions).  
  
We will the utilize the ensemble for predictions, aggregated on a regional scale, about the total C sequestration potential in Swedish agricultural soils. These predictions will include a detailed uncertainty evaluation including also the model structural uncertainty.  


# Specific tasks

## 1 Data consolidation

## 2 The models
The first step is defining what a specific model is.  
Here we will consider a SOC decomposition model as a compartmental model where compartments are in general connected with a cascade of mass fluxes and defined by a decomposition kinetic associated with each pool. The models which can present or not one or more inert pools, which are just a special case of pool with kinetic zero (and therefore present the peculiarity of simulate over time for SOC an asymptote translated above zero).  
Models can also present interactions between the pools, which makes them nonlinear. Here we define as linear a model which presents as variable only the pool masses. A nonlinear model presents other variables, usually the kinetics but in some cases something else like the input partitioning, which also vary as a function of the pools.

### 2.1 Linear models

#### 2.1.1 Models with an inert pool

#### 2.1.1 Models with no inert pool


### 2.2 Nonlinear models

### Autonomous and non autonomous models: the type of variance that they can describe


## 3 The climate scaling 
Compartmental models in general use a scaling factor, combination of soil moisture and temperature effects, to scale the decomposition kinetics of each pool.  
There are many different functions to express the impact of temperature and moisture on SOC decomposition, which can differ in their predictions. 
Each decomposition model will be associated to its own climate scaling functions during the calibration of the ensemble. 


## 4 Model calibration

### 4.1 Model initialization


### 4.2 The climate scaling effects
Since each model will be calibrated for all kinetic parameters, the original parameterization of each model will have no impact on the results. Model initialization will also have no impact, and therefore model performances will depend only on the decomposition model itself and on the climatic and edaphic scaling.  
For what concerns linear models, structures are all pretty similar as described in section [2 The models] and all define a combination of the same shape when integrated over time (which is an exponential decomposition curve). The amount of pools in a model defines how many of such shapes are combined together, varying the shape of the total SOC predicted but not substantially over the short time scale where we have data. The biggest difference is caused by the presence of very slow or inert pools, and it can become visible over very long term time scales.  
Over the relatively short (in terms of SOC kinetics) time scale of the measured data, the main differences in model fitness would therefore come from 


## 4.2 Standardizing the input estimation

## 5 Comparing models

## 6 Extrapolating national predictions from the ensemble

