---
title: "Multi-model comparison"
author: "Lorenzo Menichetti"
date: "`r Sys.Date()`"
output: pdf_document
bibliography: ../../ZotBib.bib  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aims of the project  
1. Produce aggregated national predictions on the C sequestration potential of Swedish agricultural soils with included model structural uncertainty  
2.  Understand the impact of various factors on prediction robustness 
To achieve these two goal, we will combine a selection of compartmental first-order SOC models, calibrate the whole ensemble on a set of Swedish long-term experiments, and then analyze the results of the ensemble in respect to various factors (for example climate, location, edaphic conditions).  
  
We will the utilize the ensemble for predictions, aggregated on a regional scale, about the total C sequestration potential in Swedish agricultural soils. These predictions will include a detailed uncertainty evaluation including also the model structural uncertainty.  


# Specific tasks

## 1 Data consolidation

## 2 Models

## 2.1 Model description: similarities
All models are possible to be written as:  
\begin{equation}\label{eq:general}
\frac{d\Gamma}{dt} = I + \xi \cdot A \cdot \Gamma(t), \Gamma(t=0)= \Gamma_0
\end{equation} 

Where $I$ is the inputs vector of lenght $n$, $\xi$ is the climate or edaphic scaling (either one scalar or a vector of length $n$), $A$ is the transfer matrix (square $n \times n$) and $\Gamma_0$ is the initialization vector of lenght $n$.  $\Gamma$ represents the total carbon $C$ measured, distributed across all the pools of the model.  
All models are assumed as non-autonomous and have forcing variables.  
Different models will mainly differ in:
* size ($n$)
* transfer matrix $A$, which can have for example feedbacks, not all models are necessarily a cascade  
And in the ways they estimate their forcing variables:  
* in the way the estimate the inputs, usually variable over time
* in the way they estimate the climatic scaling, also variable over time  
All these differences will interact with each other. In order to test for the differences in model structures ($n$ and $A$) without depending on the forcing variable estimation approaches, we will implement the latter into the Bayesian probabilistic model for calibration. 
The term $\xi$ can be decomposed into separate temperature $\tau$ and moisture $\psi$ effects.  


### 2.1.2 The reduction functions


### 2.1.3 The input estimation functions
Aboveground inputs are known.
Belowground inputs are estimated based on total biomass yields. Ideally, belowground (roots) inputs tend to follow a linear relationship with aboveground [@bolinderApproachEstimatingNet2007] defined by one single coefficient, the shoot to root ration $S:R$ (so the relationship crosses the origin), $I=yields \cdot S:R$.
One criticism to this approach is that plants can vary their allocation to belowground depending on their physiology, and it is possible that in more extreme treatments the relationship varies. We therefore considered as alternative method for input estimation a linear relationship including an intercept,  $I=\alpha_1 +yields  \cdot S:R$.

### 2.1.3 The exudates estimation functions
Root exudates are a relevant but also uncertain C input to the soil, and can be even more variable than root inputs. One possible way to estimate them is with a constant coefficient of total belowground inputs, as in [@bolinderApproachEstimatingNet2007]: $E=I \cdot 0.65$. The original value $0.65$ will be anyway considered uncertain.  
But in order to include the uncertainty of the estimation approach itself, we consider in our models also the alternative of including an intercept: $E= \alpha_2 + I \cdot 0.65$



# 3 Implementation of the sampling


## SOC Models general interface
The SOC model structures will all be implemented as:  
  
`SOC(t) = function(time, SOC_0, I, xi, parameters_g, parameters_l){}`
  
where `time` is the time steps of the simulation, `SOC_0`, the initial state variables, is a vector with one entry for each pool, `I` is a vector with all the inputs considered by that specific model, `xi` is the climate/edaphic reduction term, also a vector long as the time steps (`length(xi)=length(time)`).  
The argument `parameters_g` is a list containing all the model parameters that are assumed to be the same for all the sites and treatments (global), while the term `parameters_l`  is a list containing all the model parameters that are assumed to be variable for each site and treatment (local).  
**The local parameters will be only the ones defining input quality, while all other parameters will be considered global.**



## Cost function general interface
The cost function will be implemented as  
  
`fit = function(time, SOC_0, I, weather, parameters_g, parameters_l, SOC_t){}`
  
### The climatic scaling calculation

### The initialization of the SOC model

### Running the SOC model

### Calculating the cost


## The sampler
The sampler will run the cost function


# 4 Inference on the sampled parameter space



